name: Vibe OS ISO Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust (Nightly)
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-none

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso mtools binutils git

      - name: Download Limine Binary
        run: |
          git clone https://github.com/limine-bootloader/limine.git --branch=v10.x-binary --depth=1
          make -C limine

      - name: Build Kernel
        run: cargo build --release

      - name: Prepare ISO Directory
        run: |
          mkdir -p iso_root
          cp target/x86_64-unknown-none/release/vibe-os iso_root/
          cp limine.conf iso_root/
          cp limine/limine-bios.sys limine/limine-bios-cd.bin limine/limine-uefi-cd.bin iso_root/

      - name: Create ISO
        run: |
          xorriso -as mkisofs \
            -b limine-bios-cd.bin \
            -no-emul-boot -boot-load-size 4 -boot-info-table \
            -iso-level 3 \
            -V "VIBEOS" \
            iso_root -o VibeOS.iso

          ./limine/limine bios-install VibeOS.iso

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VibeOS-Bootable-ISO
          path: VibeOS.iso
